version: "3.8"

services:
  notion-chart-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Frontend
      - "3001:3001" # Backend API
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - notion-chart-network

  # 可選：添加 Redis 快取（如果需要）
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - notion-chart-network

networks:
  notion-chart-network:
    driver: bridge
