apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notion-chart-generator-cert
  namespace: default
spec:
  secretName: notion-chart-generator-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 188-166-204-94.nip.io
  dnsNames:
    - 188-166-204-94.nip.io
