apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backendconfig.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - service.yaml

images:
  - name: ghcr.io/stevelin100132/notion-chart-generator
    newTag: 1.0.5
