apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - persistent-volume.yaml
  - service.yaml

images:
  - name: ghcr.io/stevelin100132/notion-chart-generator
    newTag: ${APP_VERSION}
