apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notion-chart-snapshots-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
